### ISSUE TITLE
What are the advantages of highway over ag?

### ISSUE THREAD

**Issue by choucavalier** [tkengo/highway#18]
The silver searcher is already great, I stumbled upon your project and wondered what its advantages were over something as developed as the silver searcher (ag).
Is it the UTF-8 support?

**Comment by tkengo** [comment]
This is my opinion.
- Speed. In most case highway is over 10% faster than ag. This is because it uses more efficient algorithm to search a pattern, and it does more efficient disk I/O.
- Output order. highway can output search results with keeping file order.
- JP encoding ShiftJIS and EUC-JP support. _This is the advantage for Japanese_. Of course, highway supports also UTF-8.

In addition, I think following things are disadvantage.
- Stability. Probably highway is not stable yet because it is not mature enough as a grep tool. Sometimes it is crashed by segmentation fault.
- Functionality. ag has many options and functions, but hw doesn't.

**Comment by choucavalier** [comment]
Forgot to close but this answers my question :)
